name: go-vet-test
on: [push]
jobs:
  
  vet-test:
    name: Vet and test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
        id: go
      
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      
      - name: Get dependencies
        run: go mod verify
      
      - name: Vet
        run: go vet $(go list ./...)
      
      - name: Test
        run: go test -race -v $(go list ./...)
