name: go-vet-test
on: [push]
jobs:
  
  vet-test:
    name: Vet and test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15
        id: go
      
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      
      - name: Get dependencies
        run: go mod verify
      
      - name: Vet
        run: go vet $(go list ./...)
      
      - name: Test
        run: go test -race -v $(go list ./...)
