name: go-vet-test
on: [push]
jobs:
  
  vet-test:
    name: Vet and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - run: |
          go version
        shell: bash

      - name: Get dependencies
        run: go mod verify
      
      - name: Vet
        run: go vet $(go list ./...)
      
      - name: Test
        run: go test -race -v $(go list ./...)
